# spring specific properties
spring:
  main:
    lazy-initialization: false
    web-application-type: servlet
    banner-mode: off
  jackson:
    time-zone: UTC
    locale: en_US
  datasource:
    url: jdbc:h2:mem:dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    open-in-view: false
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true
  lifecycle:
    timeout-per-shutdown-phase: 60s

# server specific properties
server:
  port: 8080
  shutdown: graceful
  servlet:
    session:
      timeout: 60m
      cookie:
        http-only: true
    application-display-name: kafka-consumer
  compression:
    enabled: true
    min-response-size: 2KB # default value
    mime-types: "text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json, application/xml, image/jpeg, image/png, application/octet-stream"
  error:
    whitelabel:
      enabled: false

# log specific properties
logging:
  level:
    root: info
    org:
      springframework:
        boot: info
        kafka: info
